package org.example.annotation.processor;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.List;
import java.util.Objects;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;

import org.example.annotation.Generatable;

@SupportedSourceVersion(SourceVersion.RELEASE_21)
@SupportedAnnotationTypes("org.example.annotation.Generatable")
public class GeneratableProcessor extends AbstractProcessor {
    private boolean hasGenerated = false;
    
    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (hasGenerated || roundEnv.processingOver()) {
            return true;
        }
        
        var annotatedElements = roundEnv.getElementsAnnotatedWith(Generatable.class);

        var typeElements = annotatedElements.stream()
                .map(this::getTypeElement)
                .filter(Objects::nonNull)
                .toList();

        if (!typeElements.isEmpty()) {
            generateGeneratableRegistry(typeElements);
            hasGenerated = true;
        }

        return true;
    }

    private TypeElement getTypeElement(Element element) {
        return (element.getKind() == ElementKind.CLASS) ? (TypeElement) element : null;
    }

    private void generateGeneratableRegistry(List<TypeElement> typeElements) {
        try {
            JavaFileObject file = processingEnv.getFiler()
                    .createSourceFile("org.example.generator.GeneratableRegistry");

            try (Writer writer = new BufferedWriter(file.openWriter())) {
                writer.write("package org.example.generator;\n\n");
                writer.write("import java.util.List;\n\n");
                writer.write("// Auto-generated by GeneratableProcessor. Don't modify this code!\n");
                writer.write("public class GeneratableRegistry {\n");
                writer.write("    public static List<Class<?>> getAllGeneratableClasses() {\n");
                writer.write("        return List.of(\n");

                for (int i = 0; i < typeElements.size(); i++) {
                    writer.write("            " + typeElements.get(i).getQualifiedName().toString() + ".class");
                    if (i < typeElements.size() - 1) {
                        writer.write(",\n");
                    } else {
                        writer.write("\n");
                    }
                }

                writer.write("        );\n");
                writer.write("    }\n");
                writer.write("}\n");
            }
            
            processingEnv.getMessager().printMessage(
                    Diagnostic.Kind.NOTE,
                    "Successfully generated GeneratableRegistry with " + typeElements.size() + " classes"
            );
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(
                    Diagnostic.Kind.ERROR,
                    "Failed to generate registry: " + e.getMessage()
            );
        }
    }
}
